[theme]
primaryColor = "#AD9C8E"              # Muted brown for buttons/accents
backgroundColor = "#F7E6CA"           # Light beige for main background
secondaryBackgroundColor = "#E8D59E"  # Slightly darker beige for sidebar/cards
textColor = "#222222"                 # Very dark for high readability
font = "sans serif"

[server]
enableStaticServing = true
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
        